hw4: perf(cicd): ускорение GitHub Actions

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -8,20 +8,21 @@ on:
       - 'hw4'
 
 permissions:
-  contents: write 
+  contents: write
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
         with:
           submodules: true
       
-      - name: Install dependencies
+      # Установка только необходимых зависимостей
+      - name: Install minimal dependencies
         run: |
           sudo apt-get update
-          sudo apt-get install -y \
+          sudo apt-get install -y --no-install-recommends \
             cmake \
             build-essential \
             doxygen \
@@ -29,29 +30,24 @@ jobs:
       
       - name: Configure CMake
         working-directory: ./hw4/print_ip
-        run: cmake . -DPATCH_VERSION=${{ github.run_number }}
+        run: cmake -DCMAKE_BUILD_TYPE=Release -DPATCH_VERSION=${{ github.run_number }} .
       
       - name: Build
         working-directory: ./hw4/print_ip
-        run: cmake --build .
+        run: cmake --build . --parallel  # Параллельная сборка
       
       - name: Run tests
         working-directory: ./hw4/print_ip
-        run: ctest --output-on-failure
+        run: ctest --output-on-failure --parallel 4  # Параллельные тесты
       
       - name: Package
         working-directory: ./hw4/print_ip
-        run: cmake --build . --target package
+        run: cmake --build . --target package --parallel
       
       - name: Create Release and Upload Asset
         run: |
           FILE_PATH="./hw4/print_ip/print_ip-0.4.${{ github.run_number }}-Linux.deb"
-          
-          if [ ! -f "$FILE_PATH" ]; then
-            echo "Error: File $FILE_PATH not found!"
-            exit 1
-          fi
-          
+          [ ! -f "$FILE_PATH" ] && { echo "Error: File $FILE_PATH not found!"; exit 1; }
           gh release create ${{ github.ref_name }} \
             --title "Release ${{ github.ref_name }}" \
             --draft=false \
@@ -69,15 +65,10 @@ jobs:
           sed -i 's|HTML_OUTPUT\s*=\s*.*|HTML_OUTPUT = html|' Doxyfile
           doxygen Doxyfile
 
-      - name: Prepare documentation for deployment
-        run: |
-          mkdir -p gh-pages-tmp/hw4
-          cp -r ./hw4/print_ip/docs/html/* gh-pages-tmp/hw4/
-          tree gh-pages-tmp
-
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./gh-pages-tmp
-          keep_files: false
+          publish_dir: ./hw4/print_ip/docs/html
+          destination_dir: hw4
+          keep_files: true
